config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  devise_for :users

  resources :books

  get 'visitors', to: 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author, optional: true
  belongs_to :category, optional: true

  validates :title, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def get_ips
    Visitor.create(remote_ip: request.remote_ip, visit_time: Time.zone.now)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :get_ips
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  before_action :set_book, only: [:edit, :update, :destroy, :show]
  before_action :set_search, only: [:index]

  def index
    if params[:category].present?
      @books = Book.where(category_id: params[:category]).page(params[:page]).per(params[:page_limit] || 10)
    else
      @books = @q.result.page(params[:page]).per(params[:page_limit] || 10)
    end
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    author = Author.create(name: @book.author_name)
    @book.author = author

    if @book.save
      redirect_to @book, notice: 'Book created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    unless Author.where(name: @book.author_name).any?
      author = Author.create(name: @book.author_name)
      @book.author = author
    end
     
    if @book.update(book_params)
      redirect_to @book, notice: 'Book updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.delete
    redirect_to books_path, notice: 'Book deleted.'
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author_name, :publisher_name, :published_date, :unit_price, :category)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def set_search
    @q = Book.ransack(params[:q])
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @visitors = Visitor.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def get_category_name(category)
    category.present? ? Category.find(category).name : 'All'
  end

  def show_description(book)
    book.description.present? ? book.description : 'No description'
  end
end

app/views/books/_book_list.html.slim
- if books.any?
  - books.in_groups_of(4, false).each do |group|
    .grid-x.book-row
      - group.each do |book|
        == render 'item', book: book

app/views/books/_form.html.slim
= form_for @book, class: "form-horizontal" do |f|
  - if @book.errors.any?
    - @book.errors.full_messages.each do |error|
      .error = error
  .form-group
    = f.label :title, class: "col-sm-2 control-label"
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :author_name, class: "col-sm-2 control-label"
    = f.text_field :author_name, class: "form-control"
  .form-group
    = f.label :publisher_name, class: "col-sm-2 control-label"
    = f.text_field :publisher_name, class: "form-control"
  .form-group
    = f.label :published_date, class: "col-sm-2 control-label"
    = f.date_field :published_date, class: "form-control"
  .form-group
    = f.label :unit_price, class: "col-sm-2 control-label"
    = f.number_field :unit_price, class: "form-control", step: :any
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    = f.text_field :description, class: "form-control"
  = f.submit 'Save',class: "btn btn-primary btn-block"

app/views/books/_item.html.slim
.small-3.cell.book-item
  = link_to book_path(book) do
    img.cover src="#{book.cover_url? ? book.cover_url : image_url('defbookcover.jpg')}" /
  = link_to book_path(book) do
    .book-title = book.title

  - if current_user.present?
    span
      = link_to 'Edit', edit_book_path(book), id: "edit_book_#{book.id}_from_index"
    span
      = link_to ' Delete', book_path(book), method: :delete, id: "delete_book_#{book.id}_from_index", data: { confirm: 'Are you sure?' }
  .author-name = book.author_name
  p.description = book.description
  p.price
    span $
    span = book.unit_price

app/views/books/edit.html.slim
h1 Books#edit
= render 'form'

app/views/books/index.html.slim
.grid-x.search-bar
  .small-9.cell.search-left
    = search_form_for @q, :remote => true, url: books_path, :method => :get do |f|
      .grid-x
        .small-6.cell
          = f.search_field :title_or_author_name_cont, placeholder: "author, title"
        .small-3.cell
          = f.select :category_id_eq, options_from_collection_for_select(Category.all, "id", "name", nil), include_blank: "All categories"
        .small-1.cell.button-container
          = button_tag id: 'search_btn' do
            i.fi-magnifying-glass
  .small-3.cell.search-right
    = form_tag('books', id:'category_filter', remote: true, method: :get) do
      = select_tag "category", options_from_collection_for_select(Category.all, "id", "name", params[:category]), include_blank: "Select a category"
.grid-x.page-info-bar
  .small-5.cell.info-left
    = get_category_name(params[:category])
  .small-3.cell.info-right
    = form_tag('books', id:'page_limit_form', remote: true, method: :get) do
      .grid-x
        .small-4.cell
          = select_tag "page_limit", options_for_select([10, 25, 50], selected: params[:page_limit] || 10)
        .auto.cell
          span books per page
  .small-4.cell.info-page
    span#paginator_top
      = paginate @books, window: 1

#books
  = render 'book_list', books: @books

.grid-x
  .small-9.cell

  .small-3.cell
    span#paginator_btm
      = paginate @books, window: 1

app/views/books/index.js.slim
| $("#books").html("
= escape_javascript(render("book_list", books: @books))
| ");

| $("#paginator_top, #paginator_btm").html("
= escape_javascript(paginate @books)
| ");

app/views/books/new.html.slim
h1 Books#new
= render 'form'

app/views/books/show.html.slim
.grid-x.book-show
  .small-3
    img.cover-show src="#{@book.cover_url? ? @book.cover_url : image_url('defbookcover.jpg')}" /
  .small-9
    p.book-title = @book.title
    p
      span by&nbsp;
      span = @book.author_name
    p.description = show_description(@book)
    p = @book.unit_price

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  body
    == render 'shared/nav'
    - flash.each do |key, value|
      div class=("alert alert-#{key}") = value
    == yield
    == render 'shared/footer'

app/views/shared/_footer.html.slim
.footer
  .footer-contact.grid-x
    .small-8.cell
      p Do you want to sell your books?
      p Join Bookstore.com today!
    .small-4.cell
      span Follow us
      .social-icons
        i.fi-social-facebook
        i.fi-social-twitter
        i.fi-social-google-plus
  .footer-copyright.grid-x
    span copyright info

app/views/shared/_nav.html.slim
.top-bar
  .top-bar-left
    ul.dropdown.menu data-dropdown-menu=""
      = link_to books_path do
        li.menu-text
          span.title-left bookstore
          span.title-right .com
  .top-bar-right
    - if current_user.present?
      span
        = link_to "Add Book ", new_book_path, id: 'new_book_from_nav'
      span
        = link_to "Visitor List ", visitors_path
      span
        = link_to "Logout", destroy_user_session_path, method: :delete
    - else
      = link_to "Login", new_user_session_path

app/views/visitors/index.html.slim
table
  thead
    tr
      th Visitor id
      th Visitor remote ip
      th Visit time
  tbody
    - @visitors.each do |visitor|
      tr
        td
          = visitor.id
        td
          = visitor.remote_ip
        td
          = visitor.visit_time